### ISSUE TITLE
Bug. Bad implement.

### ISSUE THREAD

**Issue by aiboys** [yoshitomo-matsubara/torchdistill#214]
I found a bug in [cifa-resnet](https://github.com/yoshitomo-matsubara/torchdistill/blob/main/torchdistill/models/classification/resnet.py#L61).

I changed `Avgpool2d(8,stride=1)` to `AdaptiveAvgPool2d(1)` that is actually correct.

Besides, Thx for your contribution of opening resource.I am going to use this repo to build my own distillation algorithm. But to be honestly, it seems that there are some '' so big'' bugs in this repo. So chould you plz tell me if all your experiments are done correctly by using this repo? I am so confused about that.

**Comment by yoshitomo-matsubara** [comment]
Hi @aiboys ,

I am not sure why you consider `Avgpool2d(8, stride=1)` as a bag and bad implementation since the implementation is based the official implementation of ResNet for CIFAR datasets as given [here](https://github.com/facebookarchive/fb.resnet.torch/blob/985e569d468d23baeef5b952954dcdf3c61c5e73/models/resnet.lua#L143)

Could you also provide more info about where you find "so big" bugs in this repo? I used this repo to perform all the experiments I reported. For those reported in my torchdistill paper, I also provided log and config files for the results.

**Comment by aiboys** [comment]
Oh, I am sry. I checked my configuration file in details. I resized dataset into (224,224) which is the same as ImageNet. Since the downsample rate is 8, the avgpooling layer does not match. I also checked your CIFAR configurations where the params of Resize is 32.
| |
罗杨
|
|
***@***.***
|
签名由网易邮箱大师定制
On 1/11/2022 12:12，Yoshitomo ***@***.***> wrote：

Hi @aiboys ,

I am not sure why you consider Avgpool2d(8, stride=1) as a bag and bad implementation since the implementation is based the official implementation of ResNet for CIFAR datasets as given here

Could you also provide more info about where you find "so big" bugs in this repo? I used this repo to perform all the experiments I reported. For those reported in my torchdistill paper, I also provided log and config files for the results.
