### ISSUE TITLE
Custom Data

### ISSUE THREAD

**Issue by Holmes2002** [yoshitomo-matsubara/torchdistill#255]
Hi, I  adjusted cfg file , but when I run segmentation.py It always download pascal voc ?
How can I adjust to train in my dataset which include image and label ?

**Comment by yoshitomo-matsubara** [comment]
Hi @Holmes2002 

Please use Discussions above (instead of Issues) for questions.
As explained [here](https://github.com/yoshitomo-matsubara/torchdistill#issues--questions--requests) and [here](https://github.com/yoshitomo-matsubara/torchdistill/issues/new/choose), I want to keep Issues mainly for bug reports.
