### ISSUE TITLE
[BUG] Not supported to Nvidia 4090

### ISSUE THREAD

**Issue by allent4n** [yoshitomo-matsubara/torchdistill#367]
Please use [Discussions](https://github.com/yoshitomo-matsubara/torchdistill/discussions) to ask questions.

**Describe the bug**
When I install torchdistill==0.3.3 and torchvision==0.13.1, it did not support my cuda version (12.0).
I assume the problem is the torch library is supporting my cuda version.

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04 LTS
 - Python ver: 3.7
 - torchdistill ver: v0.3.3

**Additional context**
Is it possible if you can update some of the libraries so that those who are using the new GPU can also interact with your repo directly? Thank you.

**Comment by yoshitomo-matsubara** [comment]
Hi @allent4n 

To use torchdistill with some recent GPUs right now, you have two options:
- [Install torchdistill from the repository](https://github.com/yoshitomo-matsubara/torchdistill#install-from-this-repository-not-recommended) (Do not use scripts/configs under `legacy/` in this case)
- Create a conda environment, install older version of CUDA that is compatible with  torchvision==0.13.1, and then `pip3 install torchdistill`


As you can see in commit logs after v0.3.3, the next release of torchdistill is almost ready, but the documentation is work in progress and I cannot complete it soon because it's a very busy season for submitting/reviewing papers.

If either the 1st or 2nd options does not work for you, feel free to reopen this issue and share more details.
