### ISSUE TITLE
Is it possible to use a model with YOLO framework?

### ISSUE THREAD

**Issue by matt-sharp** [yoshitomo-matsubara/torchdistill#81]
Is it possible to use a model with YOLO framework?
Since this is written in C I'm not sure it will work with Pytorch.

**Comment by yoshitomo-matsubara** [comment]
Hi @matt-sharp ,
Technically, yes. There are some PyTorch implementations of YOLO models e.g., [DeNA/PyTorch_YOLOv3](https://github.com/DeNA/PyTorch_YOLOv3), and probably you can introduce torchdistill to the framework.

If you can provide more details such as what teacher and student models you are considering, from which layers you'd like to extract input/output for distillation, etc, I could make more concrete suggestions.

**Comment by yoshitomo-matsubara** [comment]
@matt-sharp Closing this issue as I don't see any follow-up for a while.
Open a new `Discussion` (not `Issue`) if you still have questions

**Comment by ppogg** [comment]
Dear anthor：
         Thank you for your contribution, I think dear if you have any colleagues who will introduce to the author of YOLO in the near future, compared to the people of YOLO all over the world who have asked more, I think that is a very great work！

**Comment by yoshitomo-matsubara** [comment]
Hello @ppogg 

Do you have any specific knowledge distillation method in mind? If so, feel free to create a [`Discussion`](https://github.com/yoshitomo-matsubara/torchdistill/discussions) (not here) and leave a comment.

Otherwise, I do not have any plan to add YOLO example because knowledge distillation in object detection is more challenging than other tasks as mentioned [here](https://github.com/yoshitomo-matsubara/torchdistill/issues/117#issuecomment-857673437)
